import Layout from '@/components/layout';
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
// import "node_modules/react-modal-video/scss/modal-video.scss";
import { useEffect } from 'react';
import '../public/vendor/font-awesome/css/all.min.css';
import '../public/vendor/glyphter/css/golftio.css';

import { Provider } from 'react-redux';

import store from '../redux/store';

// slick css
import 'slick-carousel/slick/slick.css';

//main css
import '@/styles/globals.scss';
import "../styles/booking/booking.scss";
import "../styles/bookingHistory/bookingHistory.scss";
import "../styles/program/program.scss";
import "../styles/program/programDetails.scss";
import "../styles/profile/profile.scss";
import "../styles/eCard/eCard.scss";

export default function App({ Component, pageProps }) {
  useEffect(() => {
    require('bootstrap/dist/js/bootstrap.bundle.min.js');
  }, []);

  if (Component.getLayout) {
    return Component.getLayout(
      <>
        <Provider store={store}>
          <Head>
            <title>GOLFTIO | Golf Club React Nextjs Template</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </Provider>
      </>
    );
  }

  return (
    <>
      <Provider store={store}>
        <Head>
          <title>GOLFTIO | Golf Club React Nextjs Template</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
        </Head>

        <Layout>
          <Component {...pageProps} />
        </Layout>
      </Provider>
    </>
  );
}
